spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: production

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
      connection-properties: "characterEncoding=utf8"
    url: jdbc:mysql://localhost/mydb
    username: userfoo
    password: secret
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      show-sql: true
      naming:
        strategy: org.hibernate.cfg.EJB3NamingStrategy
    database-platform: org.hibernate.dialect.MySQLDialect

